### ISSUE TITLE
Hyperlinks in name of laws and articles in the XML

### ISSUE THREAD

**Issue by Kjarrval** [althingi-net/lagasafn-xml#3]
If there is a hyperlink in the name of the law, for example in 12/2009, it's either untouched and/or the HTML tags are converted. The same seems to apply to names of articles (same example), although I don't know if that's intended.

**Comment by helgihg** [comment]
I agree, it's ugly and kind of useless. Previously I wasn't sure how to deal with them, but having looked at the XML again, I've concluded that references to other laws should be created by analysing the text rather than keeping original messy HTML. I believe the text should be clean, without references, at least unless those references contain more valuable information with the XML data in mind, as opposed to just being links to HTML files.

At some point I might implement references to other laws, but then they will be created by the script itself, and not copied over from the content.

Thanks for the tip. I've updated both the code and XML. They should now be clean. Please close this issue if you feel that this solution is appropriate.

**Comment by Kjarrval** [comment]
Thanks a lot!
