### ISSUE TITLE
Support for annexes

### ISSUE THREAD

**Issue by Kjarrval** [althingi-net/lagasafn-xml#4]
Probably a low priority but it might be useful in the future to support annexes (viðaukar), found for example in law 106/2000.

**Comment by helgihg** [comment]
It would be tremendously useful, yes. To be honest though, I've basically given up on it, because their format is essentially impossible to predict.

Different institutions have vastly different traditions for presenting data, not just in terms of file format but everything related to presentation - and many (possibly most) are actually far less consistent than Althingi's laws. Think of all the different possible documents from the United Nations, others from the European Union, yet others the Nordic Council, various other intranational organizations and of course; individual agreements between Iceland and just any other random party. The permutations are literally endless.

On top of that (just to kind of rub in the impossibility of it), the way that Parliament then actually includes this data into the HTML is a whole new jungle in its own right. Althingi seems to strive toward consistency, which is the very basic reason why this project is possible at all, but even with all their ambition, it's still a series of new jungles to wade through.

So, essentially, I don't think it's realistic considering the scope of the project. If most institutions that might be responsible for documents showing up in annexes start picking up standardized ways of presenting their data and Althingi starts linking to it in a predictable and consistent manner, then it might be possible. But at this point, I don't really think it is.

Please close this issue if you agree, otherwise I'm happy to discuss further.

**Comment by Kjarrval** [comment]
I wasn't thinking of it in terms of other than Alþingi's laws. From what I gather are three main different types of visual display of annexes of Alþingi's laws:
1. A special law stipulating the addition of an annex of another law (e.g. law 48/1969).
2. Where only a reference to the Law Gazette is displayed (e.g. law 88/2005).
3. Where the annexes is displayed at the bottom similar to any other chapter (kafli).

There first two are programmatically too complex to write for and probably not worth it, especially the first item due to its rarity. The third item might be too complex as well, especially regarding tables and such, so I wouldn't blame you if you closed the issue with a "wontfix". So I'll close the issue for you since I kind of agree.

**Comment by helgihg** [comment]
Quick question regarding your example nr. 1. Do you mean the text "1. gr. laga nr. 80 15. ágúst 1966" in 1. gr.?

Because if so, then I do hope to implement a process for systemically translating such strings into actual references. It's among the many ideas that I have for interesting projects once I reach 100% parsability. By parsability, I mean that the script doesn't inevitably crash because it can't handle the data. Currently, there is only one law that breaks parsability, nr. 88/1991, so I'm already at 99,94%. I'm hoping to reach 100% when the next version of the legal codex is published.

It'll be programmatically complex for sure, mostly because of inherent inconsistency in the data (especially over decades of changes in traditions in presentation), but I still believe that it's quite possible. It'll be much easier than what has already been written, for example.

So, if that's what you mean, then I certainly hope to implement that.

With regard to item nr. 2, then that wouldn't be too complex if those annexes became a consistent norm for presenting them.

With regard to item nr. 3, that's in fact the most problematic one, because although the presentation is the same as the legal codex in the sense that it's the same HTML, it's still too inconsistent in terms of what different styles actually mean. The difference between an article and a sub-article, for example, or a listing within an article or entirely different articles, and such. There is no universal agreed-upon standard for such things so it quickly gets out of hand.

Looking at the EEA-law (https://www.althingi.is/lagas/151b/1993002.html) though, it seems to me that Parliament is updating its procedures on how to present annexes in such a way, that possibly it'll become feasible at some point. Compare that with how it used to be: https://www.althingi.is/lagas/131b/1993002.html - it seems they're updating this little by little. In fact, I'll ask around about this.

It's still a wontfix for now, but it's definitely worth paying attention to if Parliament is actually making the annexes more parsable. I presume it'll take a while, but I'll keep my eyes open.
