### ISSUE TITLE
Titles might need some cleaning up

### ISSUE THREAD

**Issue by Kjarrval** [althingi-net/lagasafn-xml#5]
Code contribution which might be used to solve some current issues with titles:
1) Sup HTML elements are sometimes in titles marking footnote comments, usually about pending changes or changes in the title.
2) Brackets are wrongfully in place, their purpose being to mark a change in the title as a whole or in part.
3) HTML comments are sometimes in the title.
4) The titles sometimes have extra spaces.

The code, which may be utilised for this project, is:
`heiti_bs4 = BeautifulSoup(heiti,"lxml")
for aths in heiti_bs4.findAll(text=lambda text:isinstance(text, Comment)):
  aths.extract()

if heiti_bs4.find('sup'):
  heiti_bs4.find('sup').decompose()

heiti = heiti_bs4.get_text()
heiti = heiti.strip()
heiti = heiti.replace('[','').replace(']','') `

---
It was written in a custom script so changes in variable names or some other adaptations might be needed.

**Comment by helgihg** [comment]
Thanks for checking this out and pardon me for taking such a long time to respond.

The bad news is that it's not that simple. The good news is that I've figured out what needs to be done and already implemented it.

To elaborate;
if you only need the cleartext names of laws, your solution is fine. But one of the major design goals of this project is to be able to recreate Althingi's own legal documents (to whatever extent that's possible using consistent data in the first place), including the tracking of changes that are explained by those very brackets. By simply removing them (which again, is fine if you don't actually need them), important information is lost that would make recreation of the original documents impossible.

So I needed to delve a bit under the hood to figure this out, because of how footnotes to name changes are basically presented in the most inconvenient location possible in the original HTML. But I think I've figured it out! Please pull the most recent version of the XML files and see if they now fit your needs better.

If this solution fits your needs, please close this issue. Otherwise, I'm happy to discuss further.

**Comment by Kjarrval** [comment]
Since I've processed everything I need from the titles my needs are met already. I've looked at the XML for law 30/1954 and it looks good in case anyone else would need the information for a similar purpose.
